### ISSUE TITLE
Is it posible to convert csv back to bvh?

### ISSUE THREAD

**Issue by Dene33** [OlafHaag/bvh-toolbox#2]
Is it posible to convert csv back to bvh? Do you have existing functional for that?

**Comment by OlafHaag** [comment]
Not yet. With my current implementation, the connectivity between joints is lost during conversion to CSV. I would approach it by exporting a separate CSV file containing only the topology. It then would look like [this one ](https://github.com/OlafHaag/Flexible-Mocap-Setup/blob/master/sample_data/skeleton_template.csv), just the first 5 columns.

**Comment by Dene33** [comment]
Is there any chance that this will be implemented soon? :)

**Comment by OlafHaag** [comment]
> Is there any chance that this will be implemented soon? :)

I'll look into it this week. The process of converting the CSV files back to BVH will be less comfortable with what I've got in mind right now since you'll need 3 CSV files (1 for topology, 1 for rotations, and 1 for root translation). I did the BVH2CSV conversion to analyze the movements. Out of curiosity: What would you use the CSV2BVH conversion for? I can't think of a very useful application yet, as you could inject animation data directly into the BVHTree class instance's _frames_ data member and then write to a BVH file using its _write_file_ method.

**Comment by Dene33** [comment]
> > Is there any chance that this will be implemented soon? :)
> 
> I'll look into it this week. The process of converting the CSV files back to BVH will be less comfortable with what I've got in mind right now since you'll need 3 CSV files (1 for topology, 1 for rotations, and 1 for root translation). I did the BVH2CSV conversion to analyze the movements. Out of curiosity: What would you use the CSV2BVH conversion for? I can't think of a very useful application yet, as you could inject animation data directly into the BVHTree class instance's _frames_ data member and then write to a BVH file using its _write_file_ method.

I'm going to try to implement some machine learning stuff soon. Simplified, I want to convert 2d coordinates of estimated pose to, let's say, 3d coordinates of bones in bvh file. I need the bvh format as the output to be able to apply motion to 3d characters. Right now, I'm not sure what's the best way of doing that, but that's really nice to have as an input for machine learning algorithms the csv representation of data.

**Comment by OlafHaag** [comment]
I had a first go on an implementation. You can try it, but I remind you that this project is in alpha stage and I haven't done a lot of testing yet. So expect errors. Please write issues if you find any or make pull requests.
