### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by Dene33** [OlafHaag/bvh-toolbox#4]
How to actually use the `bvh2csv` (and `csv2bvh`) script? Trying to launch it, but getting the error of `no module named 'numpy'` Numpy installed, actually.

Should I install the` bvh-toolbox` first somehow? Also, getting error running `setup.py` - `error in bvhtoolbox setup command: ('Duplicate entry point', 'console_scripts', 'bvh2egg')`

**Comment by OlafHaag** [comment]
Thanks for reporting. I fixed some errors and tested the bvhtoolbox installation on Windows in a new Python 3.7 virtual environment. I updated the README. Please have a look and let me know if it works for you.
The converter scripts won't work on their own without installation, because they depend on files in this and other repositories.

**Comment by Dene33** [comment]
Checked some bvh files converting them to csv and back to bvh. Everything seems perfect, thank you.
